name: Upload to Intervals

on:
  push:
    branches: [ main ]
    paths:
      - "plans/**/*.json"

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --upgrade requests

      - name: Find changed plan files in this push
        id: files
        shell: bash
        run: |
          set -e
          changed=$(git diff-tree --no-commit-id --name-only -r "${{ github.sha }}" | grep '^plans/.*\.json$' || true)
          echo "raw<<EOF" >> "$GITHUB_OUTPUT"
          echo "$changed" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload each weekly plan
        if: steps.files.outputs.raw != ''
        env:
          INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
        shell: bash
        run: |
          set -e
          ok_any=0
          while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            # Skip latest.json; the weekly file already contains the data
            if [[ "$f" == "plans/latest.json" ]]; then
              echo "skip $f"
              continue
            fi
            echo "Uploading $f ..."
            python scripts/upload_plan_to_intervals.py \
              --plan "$f" \
              --athlete-id 0 \
              --tz America/Los_Angeles \
              --default-start 06:30
            ok_any=1
          done <<< "${{ steps.files.outputs.raw }}"
          if [[ $ok_any -eq 0 ]]; then
            echo "No weekly plan files to upload."
          fi
