name: Upload Week Plan to Intervals

on:
  workflow_dispatch:
    inputs:
      plan_path:
        description: "Path to plan JSON (e.g. plans/plan-2025-09-01.json)"
        required: true
        type: string
      tz:
        description: "IANA timezone for local start"
        required: true
        type: string
        default: "America/Los_Angeles"
      athlete_id:
        description: "Intervals athlete id"
        required: true
        type: string
        default: "0"
      default_start:
        description: "Local start time HH:MM for planned workouts"
        required: true
        type: string
        default: "06:00"
      dry_run:
        description: "If true, do not POST; just log"
        required: true
        type: choice
        options: ["false","true"]
        default: "false"

permissions:
  contents: read

env:
  TZ: America/Los_Angeles

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Upload plan
        env:
          INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
          PLAN_PATH: ${{ github.event.inputs.plan_path }}
          ATHLETE_ID: ${{ github.event.inputs.athlete_id }}
          TZSTR: ${{ github.event.inputs.tz }}
          DEFAULT_START: ${{ github.event.inputs.default_start }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          set -euo pipefail
          python scripts/upload_plan_to_intervals.py \
            --plan "${PLAN_PATH}" \
            --athlete-id "${ATHLETE_ID}" \
            --tz "${TZSTR}" \
            --default-start "${DEFAULT_START}" \
            $( [ "${DRY_RUN}" = "true" ] && echo --dry-run || true )
