name: Upload plan to Intervals

on:
  push:
    branches: [ main ]          # adjust branch
    paths:
      - 'plans/*.json'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine changed plan file
        id: plan
        shell: bash
        run: |
          FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep '^plans/.*\.json$' || true)
          echo "file=$(echo "$FILES" | head -n1)" >> $GITHUB_OUTPUT
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install --disable-pip-version-check --no-input requests

      - name: Upload to Intervals
        if: steps.plan.outputs.file != ''
        env:
          INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
        run: |
          echo "Changed plans:"
          echo "${{ steps.plan.outputs.files }}"
          python scripts/upload_plan_to_intervals.py \
            --plan "${{ steps.plan.outputs.file }}" \
            --athlete-id 0 \
            --default-start 17:30
