# .github/workflows/upload-intervals.yml
name: Upload to Intervals
on:
  push:
    branches: [ main ]
    paths:
      - "plans/**/*.json"
    paths-ignore:
      - "plans/drafts/**"
permissions:
  contents: read
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install --upgrade requests
      - name: Find changed plan files in this push
        id: files
        shell: bash
        run: |
          changed=$(git diff-tree --no-commit-id --name-only -r "${{ github.sha }}" | grep '^plans/.*\\.json$' | grep -v '^plans/drafts/' || true)
          echo "raw<<EOF" >> "$GITHUB_OUTPUT"; echo "$changed" >> "$GITHUB_OUTPUT"; echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Upload each weekly plan
        if: steps.files.outputs.raw != ''
        env: { INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }} }
        shell: bash
        run: |
          while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            echo "Uploading $f ..."
            python scripts/upload_plan_to_intervals.py --plan "$f" --athlete-id 0 --tz America/Los_Angeles --default-start 06:30
          done <<< "${{ steps.files.outputs.raw }}"
