name: weekly-summary

on:
  schedule:
    # 05:00 UTC each Monday ≈ Sunday night in Pacific (handles DST)
    - cron: '0 5 * * MON'
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: pip install -e .

      - name: Generate weekly summary
        env:
          INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
        run: icu-weekly-summary --athlete-id 0 --tz America/Los_Angeles --outdir reports/weekly

      - name: Commit report if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add reports/weekly
            git commit -m "chore: add weekly summary [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Capture latest report paths
        id: pick
        shell: bash
        r
