name: Generate ZWO from plan (OpenAI)

on:
  workflow_dispatch:
    inputs:
      week_start:
        description: "Week start (Monday, YYYY-MM-DD). If empty, use this week's Monday."
        required: false
        type: string
  push:
    paths:
      - "plans/plan-*.json"

permissions:
  contents: write

env:
  TZ: America/Los_Angeles

jobs:
  build-zwo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai jsonschema

      - name: Resolve plan file
        id: plan
        shell: bash
        env:
            INPUT_WEEK: ${{ github.event.inputs.week_start }}
        run: |
            set -euo pipefail
            if [[ -n "${INPUT_WEEK:-}" ]]; then
            MON="${INPUT_WEEK}"
            else
            # Monday of current week in America/Los_Angeles (no heredoc)
            MON="$(python -c 'import datetime as dt, zoneinfo; tz=zoneinfo.ZoneInfo("America/Los_Angeles"); today=dt.datetime.now(tz).date(); mon=today - dt.timedelta(days=today.weekday()); print(mon.isoformat())')"
            fi
            FILE="plans/plan-${MON}.json"
            echo "mon=${MON}"   >> "$GITHUB_OUTPUT"
            echo "file=${FILE}" >> "$GITHUB_OUTPUT"
            if [[ ! -s "$FILE" ]]; then
            echo "::error::Plan not found: $FILE"
            exit 1
            fi
            echo "Using $FILE"

      - name: Generate ZWOs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p zwo
          python scripts/gen_zwo_from_plan.py --plan "${{ steps.plan.outputs.file }}" --outdir zwo

      - name: Commit ZWOs
        run: |
          set -euo pipefail
          if git status --porcelain zwo | grep -q .; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add zwo/*.zwo
            git commit -m "feat(zwo): generate from plan"
            git push
          else
            echo "No changes to commit."
